spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000ms
    database: 0
    pool:
      jedis:
        max-active: 100
        max-idle: 10
        max-wait: 100000
        timeout: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?3useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: houcefei
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:/*.xml
  mapper-locations: classpath:/mapper/*.xml